components:
  securitySchemes:
    Token:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ResponseProduct:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    Products:
      type: object
      properties:
        success:
           type: boolean
        data:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              name:
                type: string
              price:
                type: string
              desc:
                type: string
              created_at:
                type: string
                format: date
              updated_at:
                type: string
                format: date
